### PR TITLE
refactor: make config options be consistent with the cli style

### PR DESCRIPTION
**Pull request by ttys3**
simplify `Config`, make it consistent with the cli style

1.  when users using the cli tool could just using a simple rule files, 
there's no reason to make users in other tools config the linter in a harder way.

2. `map[string]struct{}` is not a good struct for config file like `json`, `yaml` etc.

for example in yaml people will force to config like this:

```yaml
- a: {}
- b: {}
- c: {}
```

but the whole thing they wanted is just:

```yaml
- a
- b
- c
```

### CODE REVIEW

**Comment by timonwong** [comment]
> 2\. `map[string]struct{}` is not a good struct for config file like `json`, `yaml` etc.

The config is not intended to used as config file.

**Comment by timonwong** [comment]
Though simplify Config struct for better integration is good.

For golangci-lint, they have their own config struct styles, so there must be a struct conversion in between:
https://github.com/golangci/golangci-lint/pull/3144

**Comment by ttys3** [comment]
even not intended to used as config file, even it is not for end user.

when the thing can be `[]string`, why would we let people construct a `map[string]struct{}` ?

**Comment by timonwong** [comment]
> even not intended to used as config file, even it is not for end user.
> 
> when the thing can be `[]string`, why would we let people construct a `map[string]struct{}` ?
> 
> I know golangci-lint has its own config file or struct.
> 
> I mean, for Developer Experience (DX)

Yes, it's good to use string slice over sets

**Comment by ttys3** [comment]
there's another thing, since we parse the rules our self, so there's failure.
I think we should change `func NewAnalyzer(opts ...Option) *analysis.Analyzer` to 

`func NewAnalyzer(opts ...Option) (*analysis.Analyzer, error)`

then we can let the caller to determinate whether to panic or print an error message

**Comment by timonwong** [comment]
> there's another thing, since we parse the rules our self, so there's failure. I think we should change `func NewAnalyzer(opts ...Option) *analysis.Analyzer` to
> 
> `func NewAnalyzer(opts ...Option) (*analysis.Analyzer, error)`
> 
> then we can let the caller to determinate whether to panic or print an error message

I think we can move those parts in `run()`. So we can process flags & config in a more consistent way. (Since we cannot add hooks for the global fags)

**Comment by ttys3** [comment]
and also, `loggercheck.WithConfig` could split to:

`loggercheck.WithDisable` and `loggercheck.WithRules`,

we do not need to expose an `Config` struct for developers since ourselves actually not using that

**Comment by ttys3** [comment]
it is better not move those to `run()`

because `run()` will make those run multi times and event concurrently (if I'm not wrong with this)

thus, we will need introduce `sync.Once`

I do not think this is a good idea

**Comment by timonwong** [comment]
> because `run()` will make those run multi times and event concurrently (if I'm not wrong with this)

it will called only once

**Comment by ttys3** [comment]
I made a second commit, PTAL @timonwong  

https://github.com/timonwong/loggercheck/pull/22/commits/274a6466d990bef7ef22b85e3cbaaee407970983

**Pull request merged**
